### PR TITLE
Added new authentication database structure

### PR DESCRIPTION
**Pull request by Kaev**
Added new authentication database structure to auth.sql.
You can find a visualisation of the structure here: [https://i.imgur.com/K39RhOU.png](https://i.imgur.com/K39RhOU.png)

### CODE REVIEW

**Comment by minexew** [comment]
It's a bit unusual to have table names in plural

**Comment by Kaev** [comment]
> It's a bit unusual to have table names in plural

Shouldn't be a problem to change to singular if everyone approves. Would love to hear a second opinion about this before changing it though.

**Comment by minexew** [comment]
👍 To provide some concrete reasoning:
1. while _accounts_ might make more sense than _account_, this is not so obvious for tables that represent relationships instead of objects. even in your example there is an inconsistency between the pluralization in `rbac_groups_rights` x `rbac_role_rights`
2. when you keep table names singular, things can be done mechanically: foreign keys can always be `{tablename}_id`, for example
3. point 2 becomes especially relevant when you need to bring in an ORM, or if you want to do code generation or other automated processing

**Comment by Kaev** [comment]
Fair enough.

**Comment by Kaev** [comment]
> 👍 To provide some concrete reasoning:
> 
> 1. while _accounts_ might make more sense than _account_, this is not so obvious for tables that represent relationships instead of objects. even in your example there is an inconsistency between the pluralization in `rbac_groups_rights` x `rbac_role_rights`
> 2. when you keep table names singular, things can be done mechanically: foreign keys can always be `{tablename}_id`, for example
> 3. point 2 becomes especially relevant when you need to bring in an ORM, or if you want to do code generation or other automated processing

Done! :)
EDIT: Also added a new graph image to OP.

**Review by NixAJ — APPROVED** [review]

**Pull request closed without merging**
