### PR TITLE
Add clang-format configuration

### PR DESCRIPTION
**Pull request by CarwynNelson**
I am adding a `.clang-format` file to automate keeping the coding style consistent. This should help make pull requests from new contributors (like myself) fit in with the existing codebase.

My intention with this clang-format file is to be close to the style used by visual studio. Any recommendations on how to get closer to that (assuming that is a good goal) would be much appreciated.

## Note
If this is seen to be a good approach it might make sense to add instructions to a CONTRIBUTORS.md file. I'm mainly thinking:
* a note that you need clang-format version (whatever is decided) plus some instructions on how to install it
* maybe even a git hook that people need to enable that runs clang-tidy before someone commits. I think there is the `git-clang-format` utility that does this for you. I believe `git-clang-format` is bundled with clang-format.

### CODE REVIEW

**Comment by Pursche** [comment]
While I don't have experience using clang-format, I wholeheartedly support having a common format standard across the whole project, and I think that this sounds like the easiest way of ensuring it.

Can this also be used to enforce naming standards on functions and variables?
I think the standard we chose to go with (although I have to admit that I found a couple of cases where this wasn't being followed) is this:

Functions are UpperCamelCase
Variables are lowerCamelCase
If a member variable is considered internal (so private or protected I guess?) it has an appended underscore infront  of the name, i.e: _myPrivateMemberVariable

**Comment by CarwynNelson** [comment]
It doesn't look like clang-format is currently able to do most this but I've done a quick bit of research and found this.

There is a tool similar to `clang-format` called [cncc](https://github.com/mapbox/cncc/) that does just this (and only this), so if this is something we want to strictly enforce then I could look to set this up.

It hasn't been commited to in a while and I imagine that is because as of [this patch](https://github.com/llvm-mirror/clang-tools-extra/commit/89b8288d86c6b9cbe2526e8b78b8c3559a34e7e4) a lot of this functionality is now in `clang-tidy` , which is another tool that I would like to introduce so it might be worth introducing those checks at that time.

The only one that I'm not sure how to enforce is the `_` prepended to internal variable names, but I only did a few minutes of research so that might be solvable.

**Comment by NixAJ** [comment]
@Pursche @CarwynNelson How can we get this into NovusCore within the near future?

**Comment by CarwynNelson** [comment]
@NixAJ I could rebase onto master and apply the code format changes pretty easily. This wouldn't get it into the build pipeline or get the code style checking pull requests but I imagine that would be fine.

I'm happy to do this and move the pull request out of a draft if yourself and @Pursche are happy with that.

**Comment by NixAJ** [comment]
@Pursche Thoughts?

**Pull request closed without merging**
